### ISSUE TITLE
SwiftUI -> Layout Containers -> Collection containers: List

### ISSUE THREAD

**Issue by AZholtkevych** [liveviewnative/liveview-client-swiftui#110]
Doc: https://developer.apple.com/documentation/swiftui/list

**Comment by carson-katri** [comment]
List still needs to implement:
* `selection` argument, which supports a single ID or set of IDs (when in edit mode)
* `editActions` argument to enable default delete/move actions
* `children` KeyPath argument for an OutlineGroup-style list (may not be applicable to LiveView)

**Comment by carson-katri** [comment]
@shadowfacts The `selection` property may be dependent on the client-server bindings you are working on.
