### ISSUE TITLE
SwiftUI -> Layout Containers -> Presentation containers: NavigationLink

### ISSUE THREAD

**Issue by AZholtkevych** [liveviewnative/liveview-client-swiftui#124]
Doc: https://developer.apple.com/documentation/swiftui/navigationlink

**Comment by AZholtkevych** [comment]
Merged with #129

**Comment by AZholtkevych** [comment]
@shadowfacts can we close this one?

**Comment by shadowfacts** [comment]
I believe this is still in progress, pending #130 being merged
