### ISSUE TITLE
`font-weight` ignored unless `font` is passed

### ISSUE THREAD

**Issue by carson-katri** [liveviewnative/liveview-client-swiftui#131]
Currently, if you create a `<text>` element with no `font` attribute, any other supported font modifier will be ignored:

```html
<text font-weight="bold">Hello, world!</text>
```

However, the following works:

```html
<text font="body" font-weight="bold">Hello, world!</text>
```

Also, the `medium` weight is missing.

**Comment by bcardarella** [comment]
I believe we intend to remove attr modifiers in favor of the modifier syntax from #52

**Comment by bcardarella** [comment]
In other words, we want a single lane for functionality rather than two. The attr style was the original idea and I like it but once we go more than one level deep it falls apart.

**Comment by carson-katri** [comment]
Ok, makes sense, especially since the font-related modifiers can apply to any View, not just `Text`. I'll close this and the PR.
