### ISSUE TITLE
No such module PhoenixLiveViewNative

### ISSUE THREAD

**Issue by tiagodavi** [liveviewnative/liveview-client-swiftui#14]
I got stuck with this error on Xcode 13.4.1

![Screen Shot 2022-08-12 at 15 39 49](https://user-images.githubusercontent.com/1058350/184422960-1a79b673-d037-4f0f-b9f5-bbce51127a2b.png)

**Comment by cjfreeze** [comment]
I encountered the same issue on the same version of Xcode.

**Comment by shadowfacts** [comment]
Try making sure that PhoenixLiveViewNative is listed under your target in the project settings under "Frameworks, Libraries, and Embedded Content" and if not, add it (click the + button and select the package).

Sometimes when adding the package to the Xcode project, it doesn't automatiaclly add it as a dependency of the app target.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7091588/187474093-68b5f893-8c5d-48bc-beb4-f5f9dd03fbd2.png">

**Comment by cjfreeze** [comment]
![image](https://user-images.githubusercontent.com/11078691/187476310-a1aa6b63-88f8-4cfb-a15a-de3cbdabad7a.png)
Looks like it is already listed.

**Comment by shadowfacts** [comment]
Hmm, can you try cleaning (Product -> Clean Build Folder) and then re-building?

**Comment by cjfreeze** [comment]
Same build error, `no such module 'PhoenixLiveViewNative'`

**Comment by shadowfacts** [comment]
You can try quitting Xcode, deleting ~/Library/Developer/Xcode/DerivedData, relaunching Xcode, and then building again.

If that doesn't work, you can try cloning this repository and adding it your package as a local dependency by dragging the liveview-client-swiftui folder into file tree in the Xcode sidebar, and then making sure it's listed under Frameworks, Libraries, and Embedded Content as before.

And if that doesn't do it, I'm afraid I'm out of ideas, and there isn't much more I can do to diagnose this from afar.

**Comment by BryanJBryce** [comment]
@cjfreeze @tiagodavi Do your app targets match the library app target?

**Comment by petermm** [comment]
same issue..

I added PhoenixLiveViewNative as a dependency.. and then it worked..

<img width="751" alt="Screenshot 2022-09-09 at 21 01 20" src="https://user-images.githubusercontent.com/1033636/189424968-392eadba-dc0d-4ace-9bf4-7ea4b3e26bde.png">
