### ISSUE TITLE
Bindings

### ISSUE THREAD

**Issue by AZholtkevych** [liveviewnative/liveview-client-swiftui#159]
According to Brian, we have to open the discussion regarding Bindings How we can map those into SwiftUI

https://hexdocs.pm/phoenix_live_view/bindings.html

**Comment by AZholtkevych** [comment]
FYI @carson-katri

**Comment by carson-katri** [comment]
Here are some ideas for how each binding could map to SwiftUI.

> **Note** `N/A` does not mean it isn't possible to support, but instead that it doesn't map 1:1 with something from SwiftUI.

|  Binding  |  SwiftUI equivalent  |
| --------- | -------------------- |
| _Params_ |  |
| `value-*` | N/A |
| _Click Events_ |  |
| `phx-click` | [`onTapGesture(count:perform:)`](https://developer.apple.com/documentation/swiftui/view/ontapgesture(count:perform:)) |
| `phx-click-away` | N/A |
| _Form Events_ |  |
| `phx-change` | N/A |
| `phx-submit` | N/A |
| `phx-feedback-for` | N/A |
| `phx-disable-with` | N/A |
| `phx-trigger-action` | N/A |
| `phx-auto-recover` | N/A |
| _Focus Events_ |  |
| `phx-blur` | [`@FocusState`](https://developer.apple.com/documentation/swiftui/focusstate) |
| `phx-focus` | [`@FocusState`](https://developer.apple.com/documentation/swiftui/focusstate) |
| `phx-window-blur` | [`ScenePhase`](https://developer.apple.com/documentation/swiftui/scenephase) |
| `phx-window-focus` | [`ScenePhase`](https://developer.apple.com/documentation/swiftui/scenephase) |
| _Key Events_ |  |
| `phx-keydown` | [`keyboardShortcut(_:)`](https://developer.apple.com/documentation/swiftui/view/keyboardshortcut(_:)-8liec) |
| `phx-keyup` | N/A |
| `phx-window-keydown` | [`keyboardShortcut(_:)`](https://developer.apple.com/documentation/swiftui/view/keyboardshortcut(_:)-8liec) |
| `phx-window-keyup` | N/A |
| `phx-key` | N/A |
| _DOM Patching_ |  |
| `phx-mounted` | [`onAppear(action:)`](https://developer.apple.com/documentation/swiftui/view/onappear(perform:)) |
| `phx-update` | N/A |
| `phx-remove` | [`onDisappear(perform:)`](https://developer.apple.com/documentation/swiftui/view/ondisappear(perform:)) |
| _JS Interop_ |  |
| `phx-hook` | N/A |
| _Lifecycle Events_ |  |
| `phx-mounted` | [`onAppear(action:)`](https://developer.apple.com/documentation/swiftui/view/onappear(perform:)) |
| `phx-disconnected` | N/A |
| `phx-connected` | N/A |
| _Rate Limiting_ |  |
| `phx-debounce` | N/A |
| `phx-throttle` | N/A |
| _Static Tracking_ |  |
| `phx-track-static` | N/A |

**Comment by bcardarella** [comment]
You read my mind, I started looking into this over the weekend but this is a much better representation of that
