### ISSUE TITLE
Cannot build earlier than macOS 13

### ISSUE THREAD

**Issue by lordB8r** [liveviewnative/liveview-client-swiftui#160]
This limitation is not documented anywhere in the docs or the repo. The only place I'm finding it is in the package, and it seems it's because the ListRowSeparationModifier and `'listRowSeparator(_:edges:)' is only available in macOS 13.0 or newer`.

(Un)fortunately, I'm running on osx 12.6 and cannot upgrade further. Is there a way to get around this limitation? Or can we at least see the minimum requirements OS as well, needed for working on SwiftUI?

**Comment by shadowfacts** [comment]
Sorry, but unfortunately not. We're targeting iOS 16/macOS 13/the other 2022 releases as a baseline.

**Comment by carson-katri** [comment]
For reference, you can always see the minimum supported platforms in `Package.swift`: https://github.com/liveviewnative/liveview-client-swiftui/blob/8db6e44de1c95722a8778c2527c23c3fe68f459a/Package.swift#L8-L12

**Comment by bcardarella** [comment]
@lordB8r to give a bit of context here, there were changed in Swift that we needed to accomplish LVN. Backporting support would be at best very ugly.
