### ISSUE TITLE
Consolidating Packages

### ISSUE THREAD

**Issue by carson-katri** [liveviewnative/liveview-client-swiftui#173]
We could combine the Elixir and native client repositories to simplify development and setup. Let me know your thoughts on this, and if there's any major drawbacks I'm overlooking.

There would then be 1 repo per platform:
* `liveviewnative/swiftui`
    * `Package.swift`
    * `mix.exs`
    * `lib` - Elixir code
    * `Sources` - Swift code
* `liveviewnative/jetpack`
    * `settings.gradle.kts`
        * Would need to rename `lib` to something else for one of the packages, probably the Kotlin one? Both let you configure this.
    * `mix.exs`
        * Currently no Elixir Jetpack library, but that would be top level too.
    * `lib` - Elixir code
    * `client`? - Kotlin code

How does this simplify things?

## 1. Development
For example, let's say we want to add a modifier to the SwiftUI client.
Currently, we need to open 2 PRs:

1. Open a PR to `liveviewnative/live_view_native_swift_ui` with the modifier schema
2. Open a PR to `liveviewnative/liveview-client-swiftui` with the modifier struct

These need to be reviewed and merged together. Then, if we ever need to update the schema, 2 more PRs need to be opened and synced.

With a combined repository, we could simply open one PR with the necessary changes to both libraries.

## 2. Releases
When releasing, we need to make sure the versions are synchronized with each other. With the libraries being in the same repo, releases can be coordinated more easily.

## 3. Setup/DX
When a user is setting up their project to adopt LVN, they need to be aware of 2 repos per platform. If the repositories were consolidated, it would only require them to know about 1 repository for each platform they target.

Their dependencies for each platform still need to be updated separately to point to the same version.

**Comment by bcardarella** [comment]
I'm :+1: on this idea. Would also provide a framework for future clients to follow and keep everything in one tidy place. Let's discuss on standup today. I cannot think of any immediate drawbacks.

**Comment by shadowfacts** [comment]
I'm all for this. Making cross-cutting changes right now is somewhat annoying and this would dramatically simplify that. It would also clear up the naming convention for repos—right now having both `liveview-client-swiftui` and `live_view_native_swift_ui` is pretty unclear as to which is the front/back end.

**Comment by bcardarella** [comment]
I know GitHub sets up 301 redirects for renamed repos but I wonder if we can get a redirect setup for the `live_view_native_siwft_ui` repo to this one.

**Comment by bcardarella** [comment]
I may open this as a separate issue to discuss but I was thinking that for the eventual addons that can be written there will probably be same addon for swiftui, jetpack, winui3, etc... and it would be best to have a single repo that contains each client's version of the addon. Unlike the client itself which just should have the native code and the elixir code. What I would suggest as a project structure:

* `addon-name`
  * `client-name`
    * `client package information`
  * `elixir`
    * `elixir package information`

This would be better than separate platform specific client addons because likely functionality ideation can be consolidated in the same repo. Bugs could exist all clients. Client specific bugs shouldn't be overwhelming.

**Comment by bcardarella** [comment]
In addition to this conversation I think changing the name of this repo to create a convention of library names. I propose: `liveview-native-swiftui`. Then any libraries/addons that target a specific framework: `liveview-native-swiftui-<name>`. And if there is a cross framework library that encapsulates common behavior: `liveview-native-<name>` inside that repo the framework specific directory structure should exist as noted above
