### ISSUE TITLE
Carplay support

### ISSUE THREAD

**Issue by bcardarella** [liveviewnative/liveview-client-swiftui#176]
I have been public in stating that I don't want to support Carplay as I looked at is as potentially a liability if UI pushed to the client for carplay can be distracting. However, I want to validate this. After seeing that some UI views are just not permitted in certain cases I imagine the same would apply to carplay. So it may not be a concern for us from a lability perspective if Carplay itself limits which UI can be used to what is only approved.

Thoughts?

**Comment by carson-katri** [comment]
Looking at CarPlay documentation, it seems they provide certain templates to use, such as the [list template](https://developer.apple.com/documentation/carplay/cplisttemplate), instead of allowing fully customizable UIs.

I'm unsure whether you could use SwiftUI there at all.

**Comment by carson-katri** [comment]
Doesn't seem like it. You provide data to the templates using the Intents framework from what I can tell. Then you just tell the system to push/pop certain templates. If anything it would probably be a separate client from the SwiftUI client.

**Comment by bcardarella** [comment]
Ok that's a clean answer on why we can punt on this then. I'm OK with that.
