### ISSUE TITLE
Missing required module 'LVNObjC'

### ISSUE THREAD

**Issue by tiagodavi** [liveviewnative/liveview-client-swiftui#19]
Xcode 14 beta 5
![Screen Shot 2022-08-12 at 19 19 23](https://user-images.githubusercontent.com/1058350/184451851-32909706-95b4-40dd-99c6-fe5884c1f899.png)

**Comment by supernintendo** [comment]
You might try adding the `PhoenixLiveViewNative` package to Frameworks, Libraries, and Embedded Content within Xcode. I think it's supposed to do this automatically when you import a package but for some reason it doesn't always work.

![Screen Shot 2022-08-19 at 11 40 17 AM](https://user-images.githubusercontent.com/5893007/185693576-58497d1d-761f-4b76-9676-29c075a311e2.png)

**Comment by AZholtkevych** [comment]
rejecting

**Comment by AZholtkevych** [comment]
Module has been removed
