### ISSUE TITLE
SwiftUI additional views

### ISSUE THREAD

**Issue by AZholtkevych** [liveviewnative/liveview-client-swiftui#190]
We have to decide whether would we use additional views for LVN
List:

https://developer.apple.com/documentation/swiftui/renamebutton
https://developer.apple.com/documentation/swiftui/color
https://developer.apple.com/documentation/swiftui/outlinegroup
https://developer.apple.com/documentation/swiftui/disclosuregroup

**Comment by carson-katri** [comment]
FYI, there is already an issue open for `RenameButton`: #63

**Comment by AZholtkevych** [comment]
Add those to the list of SwiftUI views
