### ISSUE TITLE
Connection Error with PhoenixHTML 3.3.0

### ISSUE THREAD

**Issue by javierg** [liveviewnative/liveview-client-swiftui#195]
When using `phoenix_html` version 3.3.0, the app fails to render the connection it exist on:

https://github.com/liveviewnative/liveview-client-swiftui/blob/main/Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift#L235

The culprit being that new version of `PhoenixHTML` renders  as `<div data-phx-main ...>` instead of expected `<div data-phx-main="true" ...>`, which is what PhoenixHTML 3.2.0 renders.

Not sure if there is a reason for the exact match or if this can be loosen to just matching the attribute existence?

**Comment by bcardarella** [comment]
I think HTML spec treats the existence of the attribute as truthy so they'd be the same value but yes we are doing an exact match and should loosen that.

**Comment by bcardarella** [comment]
@carson-katri I think changing that LOC cited above to:

```swift
doc.select("div[data-phx-main]")
```

should be OK
