### ISSUE TITLE
Support multiple platform targets

### ISSUE THREAD

**Issue by bcardarella** [liveviewnative/liveview-client-swiftui#20]
I'd like to build for not just ios but all platform types
<img width="749" alt="Screen Shot 2022-08-13 at 9 05 02 AM" src="https://user-images.githubusercontent.com/18524/184495479-cbe40b3c-b922-4383-b732-d8e072b23639.png">

**Comment by AZholtkevych** [comment]
closing since it is done by @carson-katri
