### ISSUE TITLE
Restrict usage for Carplay?

### ISSUE THREAD

**Issue by bcardarella** [liveviewnative/liveview-client-swiftui#22]
@shadowfacts is there any way we can prevent LiveView Native from being used in Carplay?

**Comment by johankool** [comment]
Shouldn’t the question be the reverse? How would you even make it visible? Afaik CarPlay goes via templates only. That and entitlements to even run the apps, but also, why would you purposely disable LiveView there?

**Comment by bcardarella** [comment]
@johankool as I understand it CarPlay has very strict rules on what can be displayed when the car is in park and in gear so as to not distract the driver. With the server-side updating nature of LVN there is potential to abuse this.

**Comment by johankool** [comment]
True, but I'd argue that's up to the developer of the app to worry about, not this library.

**Comment by bcardarella** [comment]
@johankool I disagree, if this library gets a reputation for being a vector to work around Apple's restrictions they'll prevent its acceptance

**Comment by johankool** [comment]
Apple only allows for some custom UI for map-style apps, and even there it's limited to certain views like upcoming turns etc. The CarPlay apps are done with templates and don't allow for custom views anyway. Afaict the answer to "How would you even make it visible?" is "You can't."
