### ISSUE TITLE
tutorial: MyRegistry errors

### ISSUE THREAD

**Issue by bcardarella** [liveviewnative/liveview-client-swiftui#24]
<img width="259" alt="Screen Shot 2022-08-17 at 12 04 50 PM" src="https://user-images.githubusercontent.com/18524/185188438-0ca83f82-c745-4ea3-8db3-40a966c6b8c1.png">

**Comment by shadowfacts** [comment]
Update the Swift package using File -> Packages -> Update to Latest Package Versions.
