### ISSUE TITLE
Cannot open the tutorial project in Xcode

### ISSUE THREAD

**Issue by mayel** [liveviewnative/liveview-client-swiftui#32]
Any idea why I'm getting this error using Xcode Version 13.4.1 (13F100)? 

`The project at 'LVNTutorialApp.xcodeproj' cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode.`

**Comment by shadowfacts** [comment]
Ah, that's because I created the project with the Xcode 14 beta. I've corrected it to be compatible with Xcode 13.

**Comment by mayel** [comment]
Thank you :-)
