### ISSUE TITLE
Section 2, Step 3 - Incorrect version number

### ISSUE THREAD

**Issue by TMiller00** [liveviewnative/liveview-client-swiftui#35]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/8844501/188357412-336256d9-9d56-421f-b866-1f8b8a9b68dc.png">

~~Should minimum version number be `0.0.1`~~ Should the `Dependency Rule` be `Branch` and the branch equal `master`?

**Comment by shadowfacts** [comment]
Indeed it should be. Thanks for pointing that out.
