### ISSUE TITLE
Core LiveView Features To Implement

### ISSUE THREAD

**Issue by karolsluszniak** [liveviewnative/liveview-client-swiftui#37]
Hello. Upon quick experimentation I've discovered that LVN doesn't currently support `push_redirect` from the server side (it just makes the view hang).

Of course I can post a separate issue for that particular limitation but maybe - in the spirit of https://github.com/liveviewnative/liveview-client-swiftui/issues/2 - it'd be more handy to first assemble an as-exhaustive-as-possible list of core LiveView features e.g. by taking a look at docs and/or JS client source and create a list of everything that either new or seasoned LV developer should expect not to work at the moment. We then can extract them into separate issues if that'd be more handy.

- [ ] Server-side redirects (`push_redirect`)

**Comment by bcardarella** [comment]
we'll definitely need a list somewhere

**Comment by AZholtkevych** [comment]
@carson-katri could you please check this out. If not fixed, please move it to Q2

**Comment by carson-katri** [comment]
`push_navigate` is working on `main`.
