### ISSUE TITLE
User Interface Element -> Images: AsyncImage

### ISSUE THREAD

**Issue by bcardarella** [liveviewnative/liveview-client-swiftui#49]
Doc: https://developer.apple.com/documentation/swiftui/asyncimage

**Comment by carson-katri** [comment]
Note that `AsyncImage` still needs to support the following:
* `resizable` - currently is always enabled, but should be an attribute
* Customizable empty/failure phase

One possible design is something like [named slots](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#module-named-slots) in components:

```html
<asyncimage src="..." resizable="true">
  <:empty>
    <progressview />
  </:empty>
  <:failure :let={error}>
    <text>Failed with <%= error %></text>
  </:failure>
</asyncimage>
```
