### ISSUE TITLE
SwiftUI Modifiers Syntax Discussion

### ISSUE THREAD

**Issue by kgautreaux** [liveviewnative/liveview-client-swiftui#52]
This started over on the LiveViewNative Slack channel but I was asked to open a discussion issue on the repo by @bcardarella 

My brief proposals on slack as follows:

re: Modifiers.  They take a View and return a modified View so it seems to me that we should model this as an Elixir pipeline.

```elixir
defmodule WelcomeTextComponent do
  use LiveViewNative, :component

  def modifiers(core_component) do
    core_component
    |> background()
    |> linear_gradient()
    |> gradient(colors: [:red, :blue], start_point: :top, end_point: :bottom)
  end
end
```

That's pretty rough but I think it conveys the idea. It would be relatively straightforward for someone to translate from SwiftUI modifier chains into an Elixir pipeline to achieve the desired modifier chain.

If you wanted to be less explicit with naming and not have to write this as:
`<WelcomeTextComponent style={@style}>Example text</WelcomeTextComponent>`

Maybe you could curry the function if you wanted to apply the same pipeline to a different component?
`<asyncimage modifiers={&WelcomeTextComponent.modifiers/1(&1)} src={"/images/cats/#{name}" />`

If you wanted to reduce module combinatorial explosion a syntax modeled after `liveview` `JS` commands might also be considered:

```elixir
defmodule WelcomeTextLive do
  import LiveViewNative.Modifiers

  def render(assigns) do
    ~H"""
        <text modifiers={
           background()
           |> linear_gradient()
           |> gradient(colors: [:red, :blue], start_point: :top, end_point: :bottom)
          }
         style={@styles} id={#{@cat.id}}>
           #{@cat.name}
      </text>
    """
  end
end
```
`Modifiers` could be implemented as `behaviour`s to ensure that they will have their API cover all applicable modifiers for the `SwiftUI` view they receive.

A brief examination of Jetpack Compose shows it to be less pipeline like and more about passing the modifiers into the component args so maybe this isn't a great approach.  I would love to have @shadowfacts or @KronicDeth  weigh in on how feasible each of these syntaxes would be in their respective declarative UI toolkits.

**Comment by bcardarella** [comment]
I like this idea because the modifiers themselves are composable and the pipeline operator is the best way to manage deeply chained composition.

**Comment by bcardarella** [comment]
I really like the idea of using the eex short-hand expression to just compose the modifiers within the template. I do think there would need to be some "empty" component to pipe:

```heex
<text modifiers={
   view
   |> background()
   |> linear_gradient()
   |> gradient(colors: [:red, :blue], start_point: :top, end_point: :bottom)
  }>
    #{@cat.name}
</text>
```

**Comment by shadowfacts** [comment]
This is an interesting idea. I have a few thoughts:

1. I agree there would need to be a initial, empty value to start the pipeline.
2. This would essentially turn _all_ of the modifiers on a single element into a single dynamic that's sent over the wire in the diff, which may have performance implications. (This may be negligible, or it may only matter for elements with many attributes.)
3. It would require an Elixir package to maintain a list of all the SwiftUI modifiers, which I'm not a huge fan of.

**Comment by bcardarella** [comment]
As far as #3 goes, I suspect it will be inevitable. Installing a new package and keeping it in lockstep with the wrapped components on the SwiftUI side shouldn't be too big of a deal. The primary focus should be on does this make for a better dev experience. If so then we should consider it.

**Comment by bcardarella** [comment]
Good news! This is being implemented. There will be some slight tweaks but overall the piping functionality is now in the core branch as well as the elixir lib
