### ISSUE TITLE
End of "Style the Loading Screen to Match Your App" tutorial has unrelated change that causes Xcode comple error. 

### ISSUE THREAD

**Issue by zorn** [liveviewnative/liveview-client-swiftui#54]
I was working through [the tutorial](https://liveviewnative.github.io/liveview-client-swiftui/tutorials/phoenixliveviewnative/06-custom-loading-screen), and at the very end, I observed the tutorial instructions trying to have me change the return value of `lookupModifier`, but that resulted in a compile error. 

I think the change it recommends is unintended, as when I skipped it, I got the tutorial outcome I expected. 

I think this might be a bug.

<img width="500" alt="Screen Shot 2022-09-24 at 1 31 48 PM" src="https://user-images.githubusercontent.com/52168/192111345-3e7c1d75-9388-427c-9e3c-af5b1626599f.png">

<img width="500" alt="Screen Shot 2022-09-24 at 1 31 53 PM" src="https://user-images.githubusercontent.com/52168/192111352-acd573af-90df-4e2d-8c92-560d9bc45442.png">

<img width="500" alt="Screen Shot 2022-09-24 at 1 34 41 PM" src="https://user-images.githubusercontent.com/52168/192111375-2be72159-97ea-45ed-80d2-03a7b1f94b12.png">

https://github.com/liveviewnative/liveview-client-swiftui/blob/dceac9c74708ce06fbc30c3d2792756e592a19c9/Sources/PhoenixLiveViewNative/PhoenixLiveViewNative.docc/Resources/06-01-03-error.swift#L22-L23

**Comment by bcardarella** [comment]
@shadowfacts is this someting that will be addressed with the stuff you were working on yesterday?

**Comment by shadowfacts** [comment]
Whoops, forgot to update that bit of the tutorial.

Yes, the automated tool will compile the project at the end of each step, which would catch this.
