### ISSUE TITLE
SwiftUI -> User Interface Element -> Shapes: Path

### ISSUE THREAD

**Issue by AZholtkevych** [liveviewnative/liveview-client-swiftui#85]
Doc: https://developer.apple.com/documentation/swiftui/path

**Comment by AZholtkevych** [comment]
@carson-katri  please provide estimations here

**Comment by carson-katri** [comment]
@AZholtkevych This view is more likely to be implemented on the Swift side and registered via the `CustomRegistry`. Although we could support it by doing something similar to HTML's [`<svg>`](https://developer.mozilla.org/en-US/docs/Web/SVG) support, it may be best to hold off on that for now.
