### ISSUE TITLE
Make left nav clickable

### ISSUE THREAD

**Issue by xn** [liveviewnative/liveview-client-swiftui#9]
![Screen Shot 2022-08-12 at 1 54 01 PM](https://user-images.githubusercontent.com/2286/184415848-7ecfb535-e098-49d7-b9b5-89e9a50063e4.png)
I was expecting the steps to be clickable and had to figure out I had to scroll the left pane. Can we make it so that if you click some part, everything scrolls to the correct place?

**Comment by shadowfacts** [comment]
Unfortunately, this is entirely controlled by the DocC renderer.
